version: '2'
services:
  mhipsteropenid-app:
    image: mhipsteropenid
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - MICRONAUT_ENVIRONMENTS=prod
      - JDBC_URL=jdbc:postgresql://mhipsteropenid-postgresql:5432/mhipsteropenid
      - MICRONAUT_SECURITY_OAUTH2_CLIENTS_OIDC_OPENID_ISSUER=http://keycloak:9080/auth/realms/jhipster
      - MICRONAUT_SECURITY_OAUTH2_CLIENTS_OIDC_CLIENT_ID=web_app
      - MICRONAUT_SECURITY_OAUTH2_CLIENTS_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  mhipsteropenid-postgresql:
    extends:
      file: postgresql.yml
      service: mhipsteropenid-postgresql
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
